In [1]:
import dcarte 
import pandas as pd 
import iplantuml
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dcarte.__version__

'0.3.32'

In [9]:
assert dcarte.__version__ == '0.3.32'

In [3]:
dcarte.domains()

,RAW,BASE,LEGACY,PROFILE,SLEEP_STUDY,LOOKUP,BED_HABITS
0,Activity,Bed_Occupancy,Device_Type,Activity_Dailies,Diurnal,Device_Types,Bed_Occupancy
1,Appliances,Doors,Doors,Activity_Weeklies,Nocturnal,Homes,
2,Behavioural,Entryway,Entryway,Light,Withings_Nights,Patients,
3,Blood_Pressure,Habitat,Flags,Physiology_Dailies,Withings_Tidy,,
4,Door,Kitchen,Light,Physiology_Weeklies,,,
5,Encounter,Motion,Motion,Sleep_Dailies,,,
6,Environmental,Motion_New,Observation,Sleep_Weeklies,,,
7,Issue,Physiology,Physiology,Temperature,,,
8,Observation_Notes,Sleep,Temperature,,,,
9,Procedure,Transitions,Wellbeing,,,,
10,Sleep_Event,,,,,,
11,Sleep_Mat,,,,,,
12,Vital_Signs,,,,,,

In [20]:
df = dcarte.load('Motion','base')

Finished Loading Motion in:                    0.9 seconds

In [21]:
df.head()

               patient_id location_name          start_date
0  2GN1PHeHwRzNYQ7q4Nvg7g      Bathroom 2021-05-14 13:34:46
1  2GN1PHeHwRzNYQ7q4Nvg7g       Kitchen 2021-05-14 13:34:51
2  2GN1PHeHwRzNYQ7q4Nvg7g       Bedroom 2021-05-14 13:34:52
3  2GN1PHeHwRzNYQ7q4Nvg7g       Hallway 2021-05-14 13:34:55
4  2GN1PHeHwRzNYQ7q4Nvg7g        Lounge 2021-05-14 13:34:55

In [23]:
df.groupby(['patient_id','location_name']).count()

                                      start_date
patient_id             location_name
2GN1PHeHwRzNYQ7q4Nvg7g Bathroom             3443
                       Bed_in               1333
                       Bed_out              1333
                       Bedroom             20382
                       Front door           2323
...                                          ...
YYGGmsEaf2gP4JNN9kMprV Bedroom              8554
                       Front door            963
                       Hallway              3822
                       Kitchen             23454
                       Lounge              13735

[725 rows x 1 columns]

In [22]:
df.groupby(['patient_id','location_name']).count().unstack()

                       start_date                                    \
location_name           Back door Bathroom  Bed_in Bed_out  Bedroom
patient_id
2GN1PHeHwRzNYQ7q4Nvg7g        NaN   3443.0  1333.0  1333.0  20382.0
2TmRrtnsd3WisLYTmw5id1        NaN    126.0     NaN     NaN    408.0
2zbyXzYNKPwiPtjaA2L64o     3612.0  18405.0   924.0   924.0  20026.0
3LXU9Vf5dVsXtnJwxAhaN6      463.0  15532.0     NaN     NaN   3418.0
3hY7Mp7u9YPo1xMARSxLhc     5277.0  16168.0  1366.0  1366.0  18732.0
...                           ...      ...     ...     ...      ...
Xv41AaXiVYBKFAa7SLq8F5      323.0   2515.0     7.0     7.0   6706.0
XvG4pZADpDNdWsQfKrAt9a     1780.0      NaN     NaN     NaN   8376.0
YJMET4inKfFcBERma2tQRi      467.0   1396.0  1151.0  1151.0   2969.0
YQb22UBcPbedJqEiKAqvDU        NaN      9.0     NaN     NaN     12.0
YYGGmsEaf2gP4JNN9kMprV      238.0  13456.0  1266.0  1266.0   8554.0


location_name          Front door  Hallway  Kitchen   Lounge
patient_id
2GN1PHeHwRzNYQ7q4Nvg7g     2323.0   9446.0  18652.0  13426.0
2TmRrtnsd3WisLYTmw5id1       35.0    568.0    384.0    286.0
2zbyXzYNKPwiPtjaA2L64o     2395.0  39398.0  56778.0  26644.0
3LXU9Vf5dVsXtnJwxAhaN6      107.0   2735.0      NaN    641.0
3hY7Mp7u9YPo1xMARSxLhc      796.0      NaN  42128.0  84555.0
...                           ...      ...      ...      ...
Xv41AaXiVYBKFAa7SLq8F5      789.0   5456.0   7205.0  12702.0
XvG4pZADpDNdWsQfKrAt9a     1388.0  23488.0  13582.0   6092.0
YJMET4inKfFcBERma2tQRi     1215.0   4810.0   5442.0   3099.0
YQb22UBcPbedJqEiKAqvDU       39.0    118.0    604.0    779.0
YYGGmsEaf2gP4JNN9kMprV      963.0   3822.0  23454.0  13735.0

[89 rows x 9 columns]

In [14]:
df = df.query('location_name not in ["Back door","Front door"]')

In [24]:
from dcarte.utils import mine_pathway
pathway = mine_pathway(df.query('patient_id == "2GN1PHeHwRzNYQ7q4Nvg7g"'),
                  value='location_name',
                  source='Bed_out',
                  sink='Bed_in',
                  min_dur=120,
                  max_dur=1200)

In [ ]:
for pid,subset in df.groupby('patient_id'):
    tmp = mine_pathway(subset,**pathway_kwarg)

In [31]:
from dcarte.utils import timer 
@timer('pathway')
def get_pathway(df,kwargs):
    return mine_pathway(df,**kwargs)

In [ ]:
pathway_kwarg = {"value":'location_name',
                 "source":'Bed_out',
                 "sink":'Bed_in',
                 "min_dur":120,
                 "max_dur":1200 }

In [34]:
data = []
for pid,subset in df.groupby('patient_id'):
    print(pid,end=' - ')
    tmp = get_pathway(subset,pathway_kwarg)
    tmp.index = np.repeat(pid,tmp.shape[0])
    data.append(tmp)

2GN1PHeHwRzNYQ7q4Nvg7g - Finished pathway in:                           4.1 seconds
2TmRrtnsd3WisLYTmw5id1 - Finished pathway in:                           0.0 seconds
2zbyXzYNKPwiPtjaA2L64o - Finished pathway in:                           6.3 seconds
3LXU9Vf5dVsXtnJwxAhaN6 - Finished pathway in:                           0.0 seconds
3hY7Mp7u9YPo1xMARSxLhc - Finished pathway in:                          16.2 seconds
4h1dAuzg9rdrhyojwxUS26 - Finished pathway in:                          13.3 seconds
576646jHRwm4KkF9uzRnaC - Finished pathway in:                          12.0 seconds
5aQpCSrtPFyympF2G14a6c - Finished pathway in:                           0.0 seconds
5xSoeEijWNFxswzMEAih71 - Finished pathway in:                           5.7 seconds
64RLyRh1fEUutdhMnvu17d - Finished pathway in:                           1.7 seconds
6mMTWCmoha9jC4sbTojGei - Finished pathway in:                           0.0 seconds
6xrbQMkh12eYMdP7Xi1ggc - Finished pathway in:                           1.6 seconds
7CPkUFu959Rnb4pbB9YrFF - Finished pathway in:                           0.0 seconds
7DQFsc995CjkGv1Y4etBR2 - Finished pathway in:                           0.0 seconds
82jgn4MkSPaYsQZX92n9kC - Finished pathway in:                          16.1 seconds
8MzeY8ZePeGa6kFKJpXoMm - Finished pathway in:                          14.6 seconds
8rcEsVEy53VBG9eJTMqoK4 - Finished pathway in:                           0.0 seconds
965K58vYarXQTZEgss6HzT - Finished pathway in:                           1.1 seconds
9HYuS1aHmCBXidcwGhZBTm - Finished pathway in:                          47.7 seconds
9YauALfsfPs11tkX1Rb9jq - Finished pathway in:                           0.8 seconds
9k8CFpJ6MBanEoh3MXpMPU - Finished pathway in:                           0.0 seconds
A6DN3DM66D295QQkWzY43d - Finished pathway in:                           0.0 seconds
AFqqwemwCJ5ECzaXBcQFHh - Finished pathway in:                           2.3 seconds
AupBYL7RJpU4KLUmsWZ7Uz - Finished pathway in:                           0.9 seconds
B3cr4Euax91r63NSvVhrxs - Finished pathway in:                           2.1 seconds
BL3rTLVVUbXDyCxtWhSky6 - Finished pathway in:                          10.9 seconds
BLDnFyF4xzynLB7BhRd9XL - Finished pathway in:                           0.0 seconds
BjAJmKMnmScXNFfSGd5RWr - Finished pathway in:                           0.9 seconds
BqG6BCSqzJzxsiKHuMcrqr - Finished pathway in:                          33.8 seconds
CC9UHg3L6QGurrhbqv1v36 - Finished pathway in:                           0.8 seconds
DArgytxDspe3jPUMMLhnvk - Finished pathway in:                          54.2 seconds
DjyXWjqXBdL4MPDzfwNZLh - Finished pathway in:                           0.0 seconds
Dr1tnvKDk2bHG8YS21nwiR - Finished pathway in:                           0.0 seconds
EH76RUxUE8DUtjuw6qdqy1 - Finished pathway in:                           1.0 seconds
Ea5ofFVKwHmHWrZSQEd7uj - Finished pathway in:                          11.4 seconds
EpK7pZE2KYM8d99csTqE9d - Finished pathway in:                           0.0 seconds
EzjmQuxceJzLATdtyUbDn8 - Finished pathway in:                           8.7 seconds
GN6rJBMTm987Q99Zd6umgT - Finished pathway in:                          12.5 seconds
GSzwDp5WGtabtzckHQw9Ya - Finished pathway in:                           3.4 seconds
GUPoZt87k3uxPXtBJX9Q4Y - Finished pathway in:                           0.0 seconds
HCahseCCzPyFVkut5ya5Dm - Finished pathway in:                           0.4 seconds
HdozjhTxFXBhYAnKje524Q - Finished pathway in:                          10.9 seconds
Hpbmfij5E6hh19u1uKFXQT - Finished pathway in:                           1.6 seconds
HuxB79xNXzn48V3oTNmQvH - Finished pathway in:                           9.4 seconds
JCkDxjf4VxPZ9ApvwBXXhs - Finished pathway in:                           1.2 seconds
JEvSjBYo6KvDKHCGUnDNxm - Finished pathway in:                         103.3 seconds
JHX2zgJwT6PTgTUM3AvzZz - Finished pathway in:                           0.0 seconds
JHvi2gBhcufYzhmg4F1H9T - Finished pathway in:                           0.5 seconds
JPNnoXJmggJXS9PLE6mck6 - Finished pathway in:                           0.0 seconds
JQwQLzfRYX5KmetFSg69kK - Finished pathway in:                           0.0 seconds
JYN9EVX3wyv76VbubFPpUB - Finished pathway in:                          40.1 seconds
Jyn62ywXtasNk9E732LsER - Finished pathway in:                           2.4 seconds
K6HnqfpnKjDE2pRfKxE6sX - Finished pathway in:                           0.5 seconds
KGb3SK67baYUJdMVBVoLzP - Finished pathway in:                           0.0 seconds
KtDu28PYqvkTddiXFcETFZ - Finished pathway in:                           0.3 seconds
LkREF5vWKVcNDP5EkPdJu2 - Finished pathway in:                           0.1 seconds
MghE4vUbHVo6WfjSiy2FkF - Finished pathway in:                           1.4 seconds
Mhy2uUxJnCtsEZbToCDDEE - Finished pathway in:                          31.0 seconds
NQZAVtyexaA1M4Yat2xaHc - Finished pathway in:                           3.3 seconds
NVsBVXssrkn1cfSDjTQqdx - Finished pathway in:                           0.3 seconds
Nuj2WjhkRnG2zHsnpPpadw - Finished pathway in:                           0.2 seconds
PEqWC2grULEzbhEvkAWEz2 - Finished pathway in:                           0.9 seconds
PFWXtc1ZAL6okGuhVPrabe - Finished pathway in:                           0.1 seconds
Pdt1jKn38QYFu5X2CWkQ32 - Finished pathway in:                           0.1 seconds
PtSJCv5bDWvZe3f1V7wRgQ - Finished pathway in:                          25.7 seconds
R6EMvJdLnRhM4t8o3Fuqwd - Finished pathway in:                          22.8 seconds
R8amTSvAQkobnkeuWybkWL - Finished pathway in:                           1.1 seconds
RxCHTWbYDmuRtYBfVxGtfP - Finished pathway in:                           0.0 seconds
SFAVp89dUdgWxhLiGHME1a - Finished pathway in:                           0.0 seconds
SURX1xE2iymy4aexFE34yv - Finished pathway in:                           0.0 seconds
TBtq2x9LuMnZt9MmNcj1Xv - Finished pathway in:                           1.5 seconds
TDYFcFDBmhxGymqBtvKnqV - Finished pathway in:                           3.2 seconds
TTTuJeUvnGhPJBznMtCiNj - Finished pathway in:                          11.1 seconds
TwiUT1L1KSVnRdBuEywxfh - Finished pathway in:                           0.5 seconds
U2dZSjjycMm5bRNvHcLrAr - Finished pathway in:                           7.7 seconds
UDqJTeSWhVGnhHDRrodurm - Finished pathway in:                           0.0 seconds
V4H3rTBaezHnbXufvjFQmM - Finished pathway in:                           2.6 seconds
VmrLbcBzyzacPx8WBnnttf - Finished pathway in:                          25.5 seconds
WSdj9TjJMT4oqpdMvMDsgg - Finished pathway in:                          66.9 seconds
WgTjg4VRZSr4r7bCSdSetZ - Finished pathway in:                           0.0 seconds
WrXiKEAY93k5DhEinCTC6y - Finished pathway in:                           0.1 seconds
WtYLx1dEr6hHgQDg8TKcGP - Finished pathway in:                          15.4 seconds
X7dJAZjrhEa1kRFUkoZVvg - Finished pathway in:                           0.0 seconds
XsfBVz6GP7XtvhY4CiAvuf - Finished pathway in:                          33.7 seconds
Xv41AaXiVYBKFAa7SLq8F5 - Finished pathway in:                           0.0 seconds
XvG4pZADpDNdWsQfKrAt9a - Finished pathway in:                           0.0 seconds
YJMET4inKfFcBERma2tQRi - Finished pathway in:                           2.6 seconds
YQb22UBcPbedJqEiKAqvDU - Finished pathway in:                           0.0 seconds
YYGGmsEaf2gP4JNN9kMprV - Finished pathway in:                           2.2 seconds

In [43]:
data_ = pd.concat(data)

In [44]:
data_

,start_date,end_date,source,sink,transition,dur,pathway,patient_id
2,2021-05-29 04:58:00,2021-05-29 05:00:00,Bed_out,Bed_in,Bed_out>Bed_in,120.0,Bed_out>Bedroom>Bed_in,2GN1PHeHwRzNYQ7q4Nvg7g
4,2021-05-29 07:10:00,2021-05-29 07:20:00,Bed_out,Bed_in,Bed_out>Bed_in,600.0,Bed_out>Hallway>Bathroom>Bedroom>Bedroom>Bed_in,2GN1PHeHwRzNYQ7q4Nvg7g
8,2021-05-29 16:47:00,2021-05-29 16:57:00,Bed_out,Bed_in,Bed_out>Bed_in,600.0,Bed_out>Bedroom>Bedroom>Bed_in,2GN1PHeHwRzNYQ7q4Nvg7g
10,2021-05-29 17:41:00,2021-05-29 17:47:00,Bed_out,Bed_in,Bed_out>Bed_in,360.0,Bed_out>Bedroom>Bed_in,2GN1PHeHwRzNYQ7q4Nvg7g
12,2021-05-29 18:24:00,2021-05-29 18:30:00,Bed_out,Bed_in,Bed_out>Bed_in,360.0,Bed_out>Bedroom>Bedroom>Bed_in,2GN1PHeHwRzNYQ7q4Nvg7g
...,...,...,...,...,...,...,...,...
2464,2022-02-20 03:57:00,2022-02-20 03:59:00,Bed_out,Bed_in,Bed_out>Bed_in,120.0,Bed_out>Bed_in,YYGGmsEaf2gP4JNN9kMprV
2474,2022-02-21 01:50:00,2022-02-21 01:52:00,Bed_out,Bed_in,Bed_out>Bed_in,120.0,Bed_out>Bed_in,YYGGmsEaf2gP4JNN9kMprV
2488,2022-02-22 09:58:00,2022-02-22 10:00:00,Bed_out,Bed_in,Bed_out>Bed_in,120.0,Bed_out>Bed_in,YYGGmsEaf2gP4JNN9kMprV
2520,2022-02-27 06:05:00,2022-02-27 06:15:00,Bed_out,Bed_in,Bed_out>Bed_in,600.0,Bed_out>Bedroom>Hallway>Bathroom>Bathroom>Bedr...,YYGGmsEaf2gP4JNN9kMprV
2526,2022-02-27 22:54:00,2022-02-27 22:56:00,Bed_out,Bed_in,Bed_out>Bed_in,120.0,Bed_out>Bed_in,YYGGmsEaf2gP4JNN9kMprV

In [45]:
vc = data_.pathway.value_counts().to_frame()

In [46]:
vc[vc.pathway>100]

                                                    pathway
Bed_out>Bed_in                                        45078
Bed_out>Bedroom>Bedroom>Bed_in                         1597
Bed_out>Bedroom>Bed_in                                 1510
Bed_out>Bedroom>Bathroom>Bathroom>Bedroom>Bed_in       1423
Bed_out>Bathroom>Bathroom>Bedroom>Bed_in                764
Bed_out>Bedroom>Bedroom>Bedroom>Bed_in                  647
Bed_out>Bedroom>Hallway>Bathroom>Bathroom>Hallw...      529
Bed_out>Bedroom>Bathroom>Bathroom>Bathroom>Bedr...      342
Bed_out>Bedroom>Hallway>Hallway>Bedroom>Bed_in          329
Bed_out>Bathroom>Bathroom>Bed_in                        324
Bed_out>Bathroom>Bedroom>Bed_in                         285
Bed_out>Bedroom>Bedroom>Bedroom>Bedroom>Bed_in          240
Bed_out>Bedroom>Bathroom>Bedroom>Bed_in                 209
Bed_out>Bedroom>Bedroom>Bathroom>Bathroom>Bedro...      198
Bed_out>Bedroom>Bathroom>Bathroom>Bedroom>Bedro...      183
Bed_out>Bathroom>Bathroom>Bathroom>Bedroom>Bed_in       178
Bed_out>Bathroom>Bedroom>Bedroom>Bathroom>Bed_in        174
Bed_out>Bedroom>Bathroom>Bathroom>Bed_in                149
Bed_out>Hallway>Bathroom>Bathroom>Hallway>Bedro...      148
Bed_out>Bedroom>Bathroom>Bathroom>Bathroom>Bath...      139
Bed_out>Bathroom>Bathroom>Bedroom>Bedroom>Bed_in        137
Bed_out>Bedroom>Hallway>Bedroom>Bed_in                  132
Bed_out>Bathroom>Bed_in                                 102